services:
  - type: web
    name: greenroute-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: greenroute-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: greenroute-db
          property: connectionString

databases:
  - name: greenroute-db
    databaseName: greenroute_db
    user: greenroute
